# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: self-hosted

 
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.1'
        cache: 'npm'
    - name: Update Ubuntu libs
      run: sudo apt-get update -y
    - name: download chrome
      run: sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - name: Install chrome headless dependancies
      run: sudo apt install -y ./google-chrome-stable_current_amd64.deb
    - run: npm i
    - run: npm run build --if-present
    - run: npm run test-prod
